### PR TITLE
Rename untitled.md to enumerate-hosts.md

### PR DESCRIPTION
**Pull request by CSpanias**

### CODE REVIEW

**Comment by NeffIsBack** [comment]
With this PR the enumarete Hosts page is gone

image

**Comment by CSpanias** [comment]
> With this PR the enumarete Hosts page is gone
> 
> image

Not sure why is that. I just noticed the difference and changed the markdown page's name to match the rest of them:

enumerate-hosts

enumerate-null-sessions

Feel free to reject it and fix it yourself if it causes any issues!

**Comment by NeffIsBack** [comment]
I think i found the issue, we're gonna have to fix the SUMMARY.md as well i guess

image

Thanks for reporting though

**Comment by Marshall-Hallenbeck** [comment]
Thanks @CSpanias!

**Pull request merged**
