### PR TITLE
setting up tab completion

### PR DESCRIPTION
**Pull request by Adamkadaban**
https://github.com/Pennyw0rth/NetExec/pull/148#issuecomment-1868517478

### CODE REVIEW

**Comment by NeffIsBack** [comment]
It's only working for me when executing 'register-python-argcomplete nxc >> ~/.zshrc'.
Does it work on your side with just `activate-global-python-argcomplete`?

**Comment by Adamkadaban** [comment]
`activate-global-python-argcomplete` is working for me and doesn't need sudo (it just adds a file to `~/.szhenv` and `~/.bash_completion`, so it shouldn't need root perms.

Did you start a new shell after running `activate-global-python-argcomplete`? @NeffIsBack 

I tested on a new Debian 11 installation and my current Debian 12 setup. It worked on both with the instructions I listed

**Comment by NeffIsBack** [comment]
Interesting. I will test it then on Debian as well as on kali the next days. 

I tried restarting the shell and also took a look at the .zshrc file but it didn't change (even with sudo).
Maybe on kali the bash completions aren't added to the zshrc automatically?

**Comment by NeffIsBack** [comment]
Ok so i tested it on a fresh kali installation and just executing `activate-global-python-argcomplete`, but that doesn't work for me. What does the trick is `register-python-argcomplete nxc >> ~/.zshrc`. Maybe we should just stick with that, not sure what i have to do to get zsh to use the completions.

**Comment by Adamkadaban** [comment]
Yeah, looks like global autocomplete isn't working.
_Somehow_ it works on my machine, but I can't figure out how to replicate it.

I pushed individual registration for now

**Pull request merged**
